sudo: required

services: 
  - docker
before-install:
  - docker build -t 967rajkumar/client-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true 967rajkumar/client-test npm run test

after_success: 
  - docker build -t 967rajkumar/multi-client ./client
  - docker build -t 967rajkumar/multi-server ./server
  - docker build -t 967rajkumar/multi-nginx ./nginx
  - docker build -t 967rajkumar/multi-worker ./worker
  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Push images to docker hub 
  - docker push 967rajkumar/multi-client
  - docker push 967rajkumar/multi-server
  - docker push 967rajkumar/multi-nginx
  - docker push 967rajkumar/multi-worker
deploy: 
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-652522472203'
  bucket_path: 'docker-multi'
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY